# [Use Microsoft Graph to work with Excel](concepts\use-microsoft-graph-to-work-with-excel.md)
## [Manage sessions in Excel with Microsoft Graph](concepts\manage-sessions-in-excel-with-microsoft-graph.md)
## [Display a chart image in Excel with Microsoft Graph](concepts\display-a-chart-image-in-excel-with-microsoft-graph.md)
## [Use workbook functions in Excel with Microsoft Graph](concepts\use-functions-in-excel-with-microsoft-graph.md)
## [Update a range format in Excel with Microsoft Graph](concepts\update-range-format-in-excel-with-microsoft-graph.md)
## [Write data to an Excel workbook with Microsoft Graph](concepts\write-to-excel-workbook-with-microsoft-graph.md)
